"""add final_score_sent

Revision ID: 01d69363e610
Revises: 2abb3c9cd816
Create Date: 2026-04-03 19:23:52.409075

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01d69363e610"
down_revision: str | Sequence[str] | None = "2abb3c9cd816"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    cols = {c["name"] for c in sa.inspect(conn).get_columns("games")}
    if "final_score_sent" not in cols:
        op.add_column("games", sa.Column("final_score_sent", sa.Boolean(), nullable=True))
    indexes = {i["name"] for i in sa.inspect(conn).get_indexes("games")}
    if "ix_games_final_score_sent" not in indexes:
        op.create_index(op.f("ix_games_final_score_sent"), "games", ["final_score_sent"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_final_score_sent"), table_name="games")
    op.drop_column("games", "final_score_sent")
    # ### end Alembic commands ###
