"""Test migration for health check validation

Revision ID: 2ca735cdaad1
Revises: dd5c0d3a6432
Create Date: 2025-09-06 20:32:45.929014

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2ca735cdaad1'
down_revision: str | Sequence[str] | None = 'dd5c0d3a6432'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
