"""add play-by-play tables

Revision ID: cbc1308ba394
Revises: 01d69363e610
Create Date: 2026-04-04 00:53:20.895430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc1308ba394'
down_revision: Union[str, Sequence[str], None] = '01d69363e610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inning_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half', sa.String(), nullable=False),
    sa.Column('channel_message_id', sa.Integer(), nullable=True),
    sa.Column('group_message_id', sa.Integer(), nullable=True),
    sa.Column('footer_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'inning', 'half')
    )
    op.create_index(op.f('ix_inning_posts_game_id'), 'inning_posts', ['game_id'], unique=False)
    op.create_table('play_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('at_bat_index', sa.Integer(), nullable=False),
    sa.Column('group_message_id', sa.Integer(), nullable=False),
    sa.Column('last_description', sa.Text(), nullable=False),
    sa.Column('last_event', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'at_bat_index')
    )
    op.create_index(op.f('ix_play_messages_game_id'), 'play_messages', ['game_id'], unique=False)
    op.create_table('playbyplay_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_play_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbyplay_sessions_active'), 'playbyplay_sessions', ['active'], unique=False)
    op.create_index(op.f('ix_playbyplay_sessions_game_id'), 'playbyplay_sessions', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbyplay_sessions_game_id'), table_name='playbyplay_sessions')
    op.drop_index(op.f('ix_playbyplay_sessions_active'), table_name='playbyplay_sessions')
    op.drop_table('playbyplay_sessions')
    op.drop_index(op.f('ix_play_messages_game_id'), table_name='play_messages')
    op.drop_table('play_messages')
    op.drop_index(op.f('ix_inning_posts_game_id'), table_name='inning_posts')
    op.drop_table('inning_posts')
    # ### end Alembic commands ###
