"""Add transaction tables and user preferences

Revision ID: f32aafeb1786
Revises: 2ca735cdaad1
Create Date: 2025-09-15 00:08:04.862017

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f32aafeb1786'
down_revision: str | Sequence[str] | None = '2ca735cdaad1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('from_team_name', sa.String(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_name', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('type_description', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_from_team_id'), 'transactions', ['from_team_id'], unique=False)
    op.create_index(op.f('ix_transactions_notification_sent'), 'transactions', ['notification_sent'], unique=False)
    op.create_index(op.f('ix_transactions_person_id'), 'transactions', ['person_id'], unique=False)
    op.create_index(op.f('ix_transactions_to_team_id'), 'transactions', ['to_team_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_type_code'), 'transactions', ['type_code'], unique=False)
    op.create_table('user_transaction_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('trades', sa.Boolean(), nullable=True),
    sa.Column('signings', sa.Boolean(), nullable=True),
    sa.Column('recalls', sa.Boolean(), nullable=True),
    sa.Column('options', sa.Boolean(), nullable=True),
    sa.Column('injuries', sa.Boolean(), nullable=True),
    sa.Column('activations', sa.Boolean(), nullable=True),
    sa.Column('releases', sa.Boolean(), nullable=True),
    sa.Column('status_changes', sa.Boolean(), nullable=True),
    sa.Column('other', sa.Boolean(), nullable=True),
    sa.Column('major_league_only', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_transaction_preferences_chat_id'), 'user_transaction_preferences', ['chat_id'], unique=False)
    op.create_index(op.f('ix_user_transaction_preferences_id'), 'user_transaction_preferences', ['id'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_user_transaction_preferences_id'), table_name='user_transaction_preferences')
    op.drop_index(op.f('ix_user_transaction_preferences_chat_id'), table_name='user_transaction_preferences')
    op.drop_table('user_transaction_preferences')
    op.drop_index(op.f('ix_transactions_type_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_team_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_person_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_notification_sent'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_team_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
